### ISSUE TITLE
Issue in library while executing the code

### ISSUE THREAD

**Issue by jitendrapshreemali** [marufaytekin/MatrixMultiply#1]
While trying to execute MatrixMultiply.java I am facing library issue of LogFactory. Kindly see the list below in this issue:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:165)
	at com.lendap.hadoop.MatrixMultiply.main(MatrixMultiply.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 2 more

**Comment by marufaytekin** [comment]
I think it is the version of apache commons library. They removed LogFactory from the version you are using in your runtime. You can pin the version of apache commons that has LogFactory in your pom.xml or find the Log factory library package and use it as a dependency. Another solution would be to upgrade the Hadoop library versions in pom.xml.
